# meta:
#   engine: 4.0.5
#   version: 1.0
#   author: Steven Eisinger

# V2 TODOS:
#   TODO: Leave P1 free for nice!view CS pin
#   TODO: Move reset button (maybe a sidways one)
#   TODO: Bigger battery slide switch
#   TODO: Standoff location for acrylic screen window
#   TODO: Wire key matrix to use 6x7 pins (up to 42) instead of 5x10 (up to 60)
#   TODO: Widen mounting holes to accomodate a full m2 spacer through the pcb?
#   TODO: Move mounting holes so that they don't interfere with diodes
#   TODO: Add VIK connector

#
# Define unit constants
#
units:
  # split
  SPLIT_ROTATION: -14
  SPLIT_DISTANCE: 64*2  # measured from inter-index distance

  # column stagger
  COLUMN_PINKY_STAGGER: 2
  COLUMN_RING_STAGGER: 10.5
  COLUMN_MIDDLE_STAGGER: 3
  COLUMN_INDEX_STAGGER: -5
  COLUMN_INNER_STAGGER: -3.5

  # thumbfan common
  THUMBFAN_ROT: 0
  THUMBFAN_X: 0
  THUMBFAN_Y: -1u + COLUMN_INNER_STAGGER

  # thumbfan outer
  THUMBFAN_OUTER_ROT: 0
  THUMBFAN_OUTER_SPLAY: 0
  THUMBFAN_OUTER_X: 0
  THUMBFAN_OUTER_Y: 0

  # thumbfan middle
  THUMBFAN_MIDDLE_ROT: 0
  THUMBFAN_MIDDLE_SPLAY: -16.5
  THUMBFAN_MIDDLE_X: 0
  THUMBFAN_MIDDLE_Y: 0

  # thumbfan inner
  THUMBFAN_INNER_ROT: 0
  THUMBFAN_INNER_SPLAY: -16.5
  THUMBFAN_INNER_STAGGER: 0
  THUMBFAN_INNER_X: 0
  THUMBFAN_INNER_Y: 0

  # screw radius
  SCREW_SIZE: 1.6
  SCREW_BORDER: SCREW_SIZE + 1.3
  STANDOFF_SIZE: 4

  # board parameters
  BOARD_FILLET: 1

  # case parameters
  BOTTOM_THICKNESS: 2
  WALL_THICKNESS: 5

  # plate parameters
  PLATE_THICKNESS: 1.5
  PLATE_EXTENSION: 0

#
# Define key locations
#
# matrix: finger matrix (excluding thumbs)
# thumbfan: thumb keys
#
points:
  zones:
    matrix:
     # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -130]
      columns:
        outer:
          key:
            column_net: P14
          rows:
            bottom.skip: true
        pinky:
          key:
            stagger: COLUMN_PINKY_STAGGER
            column_net: P16
        ring:
          key:
            stagger: COLUMN_RING_STAGGER
            column_net: P10
        middle:
          key:
            stagger: COLUMN_MIDDLE_STAGGER
            column_net: P7
        index:
          key:
            stagger: COLUMN_INDEX_STAGGER
            column_net: P8
        inner:
          key:
            stagger: COLUMN_INNER_STAGGER
            column_net: P9
      rows:
        bottom:
          row_net: P21
          mirror.row_net: P1
        home:
          row_net: P20
          mirror.row_net: P0
        top:
          row_net: P19
          mirror.row_net: P4
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        rotate: THUMBFAN_ROT
        shift: [THUMBFAN_X, THUMBFAN_Y]
      columns:
        outer:
          key:
            splay: THUMBFAN_OUTER_SPLAY
            rotate: THUMBFAN_OUTER_ROT
            shift: [THUMBFAN_OUTER_X, THUMBFAN_OUTER_Y]
            column_net: P7
        middle:
          key:
            splay: THUMBFAN_MIDDLE_SPLAY
            rotate: THUMBFAN_MIDDLE_ROT
            origin: [-0.5u, -0.5u]
            shift: [THUMBFAN_MIDDLE_X, THUMBFAN_MIDDLE_Y]
            column_net: P8
        inner:
          key:
            splay: THUMBFAN_INNER_SPLAY
            rotate: THUMBFAN_INNER_ROT
            stagger: THUMBFAN_INNER_STAGGER
            origin: [-0.5u, -0.5u]
            shift: [THUMBFAN_INNER_X, THUMBFAN_INNER_Y]
            column_net: P9
      rows:
        thumb:
          row_net: P15
          mirror.row_net: P6
  rotate: SPLIT_ROTATION
  mirror:
    ref: matrix_index_home
    distance: SPLIT_DISTANCE

#
# Define outlines for the plate
#
outlines:
  demo:
    - what: rectangle
      where: true
      size: 1u - 1
  board_raw:
    - what: rectangle
      where: true
      asym: source
      size: 1u + 2
    - what: rectangle
      where:
        ref: thumbfan_outer_thumb
        shift: [0.25u, 0.3u]
      asym: both
      size: [1.5u + 2, 1u + 2]
    - what: rectangle
      where:
        ref: thumbfan_inner_thumb
        shift: [-1u, 0]
      asym: both
      size: [2u + 2, 1u + 2]
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [0, -0.3u]
      asym: both
      size: 1u + 2
    - what: rectangle
      where:
        ref: matrix_middle_top
        shift: [1u, 0]
      asym: both
      size: [3u + 2, 1u + 2]
    # - what: rectangle
    #   where:
    #     ref: matrix_ring_bottom
    #     shift: [1u, 0]
    #   asym: both
    #   size: [3u + 2, 1u + 2]
    # - what: rectangle
    #   where:
    #     ref: matrix_middle_top
    #     shift: [-2u, 0]
    #   asym: both
    #   size: [3u + 2, 1u + 2]
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5u + 1, 1u]
        - ref: mirror_matrix_inner_top
          shift: [0.5u + 1, 1u]
        - ref: mirror_matrix_inner_bottom
          shift: [0.5u + 1, 1u - 3]
        - ref: matrix_inner_bottom
          shift: [0.5u + 1, 1u - 3]
  board:
    - what: outline
      name: board_raw
      fillet: BOARD_FILLET
  case_outline:
    - what: outline
      name: board
      expand: WALL_THICKNESS
  plate_outline:
    - what: outline
      name: board
      expand: PLATE_EXTENSION
  wall: [
    +case_outline,
    -plate_outline,
  ]
  mounting_holes_inner:
    # Screw holes
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [matrix_inner_top]
        shift: [-0.5u, -0.3u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [mirror_matrix_inner_top]
        shift: [-0.5u, -0.3u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [matrix_outer_top]
        shift: [0.5u, -0.3u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [mirror_matrix_outer_top]
        shift: [0.5u, -0.3u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [matrix_inner_bottom]
        shift: [-0.5u, -0.25u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [mirror_matrix_inner_bottom]
        shift: [-0.5u, -0.25u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.4u, 0.5u]
    - what: circle
      radius: SCREW_SIZE
      where:
        ref: [mirror_matrix_pinky_bottom]
        shift: [0.4u, 0.5u]
  mounting_holes_outer:
    # Screw holes
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [matrix_inner_top]
        shift: [-0.5u, -0.3u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [mirror_matrix_inner_top]
        shift: [-0.5u, -0.3u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [matrix_outer_top]
        shift: [0.5u, -0.3u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [mirror_matrix_outer_top]
        shift: [0.5u, -0.3u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [matrix_inner_bottom]
        shift: [-0.5u, -0.25u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [mirror_matrix_inner_bottom]
        shift: [-0.5u, -0.25u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.4u, 0.5u]
    - what: circle
      radius: SCREW_BORDER
      where:
        ref: [mirror_matrix_pinky_bottom]
        shift: [0.4u, 0.5u]
  m2_holes:
    # Screw holes
    - what: circle
      radius: 1
      where:
        ref: [matrix_inner_top]
        shift: [-0.5u, -0.3u]
    - what: circle
      radius: 1
      where:
        ref: [mirror_matrix_inner_top]
        shift: [-0.5u, -0.3u]
    - what: circle
      radius: 1
      where:
        ref: [matrix_outer_top]
        shift: [0.5u, -0.3u]
    - what: circle
      radius: 1
      where:
        ref: [mirror_matrix_outer_top]
        shift: [0.5u, -0.3u]
    - what: circle
      radius: 1
      where:
        ref: [matrix_inner_bottom]
        shift: [-0.5u, -0.25u]
    - what: circle
      radius: 1
      where:
        ref: [mirror_matrix_inner_bottom]
        shift: [-0.5u, -0.25u]
    - what: circle
      radius: 1
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.4u, 0.5u]
    - what: circle
      radius: 1
      where:
        ref: [mirror_matrix_pinky_bottom]
        shift: [0.4u, 0.5u]
  mounting_holes: [
    +mounting_holes_outer,
    -mounting_holes_inner,
  ]
  # cutouts for the keys to be used in plate generation
  keywell_mx:
    - what: rectangle
      where: true
      asym: source
      size: 1u + 2
    - what: rectangle
      where:
        ref: [thumbfan_outer_thumb]
        shift: [0, 0.5u]
      asym: both
      size: 1u + 2
  cutouts_mx:
    - what: rectangle
      where: true
      asym: source
      size: 14
  cutouts_choc:
    - what: rectangle
      where: true
      asym: source
      size: 13.8
  plate_mx: [
    +plate_outline,
    -cutouts_mx,
  ]
  plate_choc: [
    +plate_outline,
    -cutouts_choc,
  ]
  promicro_cutout:
    - what: rectangle
      where:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        shift: [0, 10.215]
      size: [28, 42]
  usbc_cutout:
    - what: rectangle
      where:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        shift: [0, 29 + WALL_THICKNESS/2]
      size: [12.5, 2*WALL_THICKNESS]
  battery_switch_cutout:
    - what: rectangle
      where:
        ref.aggregate.parts: [mirror_matrix_pinky_top]
        shift: [0.25u, 0.5u + 6.5]
        rotate: -15.5
      size: [12.5, 4*WALL_THICKNESS]


#
# Define the PCB, using a pro-micro layout
#
pcbs:
  fairyboard:
    outlines:
      fairyboard_pcb_outline:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap: true
      choc_hotswap:
        what: choc
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          hotswap: true
        adjust:
          rotate: 180
      diodes_left:
        what: diode_smt_bottom
        where: -/mirror/
        adjust:
          shift: [-4, 0.5u - 1]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      diodes_right:
        what: diode_smt_bottom
        where: /mirror/
        adjust:
          shift: [4, 0.5u - 1]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      # Microcontroller
      mcu:
        what: promicro
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, -3.41]
          rotate: -90
        params:
          orientation: down
      # nice!view screen
      display:
        what: nice_view
        params:
          MOSI: P2
          SCK: P3
          CS: P1
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, -4.41]
      # Four Pin Reset Button
      reset:
        what: reset_switch_tht_top
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-13.5, 15]
          rotate: 90
      # Battery switch
      battery_switch:
        what: slider
        params:
          from: RAW
          to: B+
        where:
          ref.aggregate.parts: [mirror_matrix_pinky_top]
          shift: [0.25u, 0.5u + 6.5]
          rotate: -15.5
      # Battery connector
      battery_connector:
        what: jstph
        params:
          pos: B+
          neg: GND
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [15, -8]
      # VIK keyboard connector
      vik_in:
        what: vik_in
        params:
          V3V: RAW # TODO
          GND: GND # TODO
          SDA: P4 # TODO
          SCL: P5 # TODO
          RGB_LED_OUT: P6
          V5V: RAW # TODO
          GPIO1: P7 # TODO
          MOSI: P2
          GPIO2: P8 # TODO
          SPI_CS: P1
          MISO: P9 # TODO
          SCLK: P3
      # Screw holes
      hole_top_inner_left:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [-0.5u, -0.3u]
      hole_top_inner_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_top]
          shift: [-0.5u, -0.3u]
      hole_top_outer_left:
        what: mountinghole
        where:
          ref: [matrix_outer_top]
          shift: [0.5u, -0.3u]
      hole_top_outer_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_outer_top]
          shift: [0.5u, -0.3u]
      hole_bot_inner_left:
        what: mountinghole
        where:
          ref: [matrix_inner_bottom]
          shift: [-0.5u, -0.25u]
      hole_bot_inner_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_bottom]
          shift: [-0.5u, -0.25u]
      hole_bot_outer_left:
        what: mountinghole
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.4u, 0.5u]
      hole_bot_outer_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_pinky_bottom]
          shift: [0.4u, 0.5u]

#
# Case
#
cases:

  # common bottom for all cases
  _bottom:
    - name: case_outline
      extrude: BOTTOM_THICKNESS

  # wall construction
  _wall_low:
    - name: wall
      extrude: BOTTOM_THICKNESS + 4.6
  _wall_mid_mx:
    - name: wall
      extrude: BOTTOM_THICKNESS + 9.6
  _wall_high_mx:
    - name: wall
      extrude: BOTTOM_THICKNESS + 15.8

  # standoff construction
  mounting_holes:
    - name: mounting_holes
      extrude: BOTTOM_THICKNESS + 4

  # plate
  plate_mx:
    - name: plate_mx
      extrude: PLATE_THICKNESS

  # final cases
  case_lowpro:
    - what: case
      name: mounting_holes
      operation: add
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall_low
      operation: add
  case_midpro_mx:
    - what: case
      name: mounting_holes
      operation: add
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall_mid_mx
      operation: add
  case_hipro_mx:
    - what: case
      name: mounting_holes
      operation: add
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall_high_mx
      operation: add
