meta:
  engine: 4.1.0
  version: 1.0
  author: Steven Eisinger (restive.engines)

#---------------------------------------------------------------------------------------------------
# Define unit constants
units:
  # split
  SPLIT_ROTATION: -14
  SPLIT_DISTANCE: 64*2  # measured from inter-index distance

  # column stagger
  COLUMN_PINKY_STAGGER: 2
  COLUMN_RING_STAGGER: 10.5
  COLUMN_MIDDLE_STAGGER: 3
  COLUMN_INDEX_STAGGER: -5
  COLUMN_INNER_STAGGER: -3.5

  # thumbfan common
  THUMBFAN_ROT: 0
  THUMBFAN_X: 0
  THUMBFAN_Y: -1u + COLUMN_INNER_STAGGER

  # thumbfan outer
  THUMBFAN_OUTER_ROT: 0
  THUMBFAN_OUTER_SPLAY: 0
  THUMBFAN_OUTER_X: 0
  THUMBFAN_OUTER_Y: 0

  # thumbfan middle
  THUMBFAN_MIDDLE_ROT: 0
  THUMBFAN_MIDDLE_SPLAY: -16.5
  THUMBFAN_MIDDLE_X: 0
  THUMBFAN_MIDDLE_Y: 0

  # thumbfan inner
  THUMBFAN_INNER_ROT: 0
  THUMBFAN_INNER_SPLAY: -16.5
  THUMBFAN_INNER_STAGGER: 0
  THUMBFAN_INNER_X: 0
  THUMBFAN_INNER_Y: 0

  # screw diameter
  SCREW_SIZE: 2.4
  SCREW_BORDER: 3.2

  # board parameters
  BOARD_FILLET: 1.1

  # case parameters
  BOTTOM_THICKNESS: 2
  WALL_THICKNESS: 3

  # plate parameters
  PLATE_THICKNESS: 1.5
  PLATE_EXTENSION: 0

#---------------------------------------------------------------------------------------------------
# Define key locations
#   matrix: finger matrix (excluding thumbs)
#   thumbfan: thumb keys
points:
  zones:
    matrix:
     # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -130]
      columns:
        outer:
          rows.top:
            row_net: ROW2
            mirror.row_net: ROW5
            column_net: COL1
          rows.home:
            row_net: ROW3
            mirror.row_net: ROW6
            column_net: COL1
          rows.bottom.skip: true
        pinky:
          key:
            stagger: COLUMN_PINKY_STAGGER
          rows.top:
            row_net: ROW2
            mirror.row_net: ROW5
            column_net: COL2
          rows.home:
            row_net: ROW3
            mirror.row_net: ROW6
            column_net: COL2
          rows.bottom:
            row_net: ROW4
            mirror.row_net: ROW7
            column_net: COL1
        ring:
          key:
            stagger: COLUMN_RING_STAGGER
          rows.top:
            row_net: ROW2
            mirror.row_net: ROW5
            column_net: COL3
          rows.home:
            row_net: ROW3
            mirror.row_net: ROW6
            column_net: COL3
          rows.bottom:
            row_net: ROW4
            mirror.row_net: ROW7
            column_net: COL2
        middle:
          key:
            stagger: COLUMN_MIDDLE_STAGGER
          rows.top:
            row_net: ROW2
            mirror.row_net: ROW5
            column_net: COL4
          rows.home:
            row_net: ROW3
            mirror.row_net: ROW6
            column_net: COL4
          rows.bottom:
            row_net: ROW4
            mirror.row_net: ROW7
            column_net: COL3
        index:
          key:
            stagger: COLUMN_INDEX_STAGGER
          rows.top:
            row_net: ROW1
            column_net: COL5
            mirror.column_net: COL4
          rows.home:
            row_net: ROW2
            mirror.row_net: ROW5
            column_net: COL5
          rows.bottom:
            row_net: ROW3
            mirror.row_net: ROW6
            column_net: COL5
        inner:
          key:
            stagger: COLUMN_INNER_STAGGER
          rows.top:
            row_net: ROW1
            column_net: COL6
            mirror.column_net: COL3
          rows.home:
            row_net: ROW2
            mirror.row_net: ROW5
            column_net: COL6
          rows.bottom:
            row_net: ROW3
            mirror.row_net: ROW6
            column_net: COL6
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        rotate: THUMBFAN_ROT
        shift: [THUMBFAN_X, THUMBFAN_Y]
      columns:
        outer:
          key:
            splay: THUMBFAN_OUTER_SPLAY
            rotate: THUMBFAN_OUTER_ROT
            shift: [THUMBFAN_OUTER_X, THUMBFAN_OUTER_Y]
            column_net: COL4
        middle:
          key:
            splay: THUMBFAN_MIDDLE_SPLAY
            rotate: THUMBFAN_MIDDLE_ROT
            origin: [-0.5u, -0.5u]
            shift: [THUMBFAN_MIDDLE_X, THUMBFAN_MIDDLE_Y]
            column_net: COL5
        inner:
          key:
            splay: THUMBFAN_INNER_SPLAY
            rotate: THUMBFAN_INNER_ROT
            stagger: THUMBFAN_INNER_STAGGER
            origin: [-0.5u, -0.5u]
            shift: [THUMBFAN_INNER_X, THUMBFAN_INNER_Y]
            column_net: COL6
      rows:
        thumb:
          row_net: ROW4
          mirror.row_net: ROW7
  rotate: SPLIT_ROTATION
  mirror:
    ref: matrix_index_home
    distance: SPLIT_DISTANCE

#---------------------------------------------------------------------------------------------------
# Define outlines for the plate
outlines:
  demo:
    - what: rectangle
      where: true
      size: 1u - 1
  board_connector:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5u + 1, 1u]
        - ref: mirror_matrix_inner_top
          shift: [0.5u + 1, 1u]
        - ref: mirror_matrix_inner_bottom
          shift: [0.5u + 1, 1u - 3]
        - ref: matrix_inner_bottom
          shift: [0.5u + 1, 1u - 3]
  board_connector_cutout:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5u + 1 + WALL_THICKNESS, 1u + (WALL_THICKNESS+1)]
        - ref: mirror_matrix_inner_top
          shift: [0.5u + 1 + WALL_THICKNESS, 1u + (WALL_THICKNESS+1)]
        - ref: mirror_matrix_inner_bottom
          shift: [0.5u + 1 + WALL_THICKNESS, 1u - 3 - (WALL_THICKNESS+0.1)]
        - ref: matrix_inner_bottom
          shift: [0.5u + 1 + WALL_THICKNESS, 1u - 3 - (WALL_THICKNESS+0.1)]
  board_connector_extended:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5u + 1, 1u + (WALL_THICKNESS+1)]
        - ref: mirror_matrix_inner_top
          shift: [0.5u + 1, 1u + (WALL_THICKNESS+1)]
        - ref: mirror_matrix_inner_bottom
          shift: [0.5u + 1, 1u - 3 - (WALL_THICKNESS+0.1)]
        - ref: matrix_inner_bottom
          shift: [0.5u + 1, 1u - 3 - (WALL_THICKNESS+0.1)]
  board_raw:
    - what: rectangle
      where: true
      asym: source
      size: 1u + 2
    - what: rectangle
      where:
        ref: thumbfan_outer_thumb
        shift: [0.25u, 0.3u]
      asym: both
      size: [1.5u + 2, 1u + 2]
    - what: rectangle
      where:
        ref: thumbfan_inner_thumb
        shift: [-1u, 0]
      asym: both
      size: [2u + 2, 1u + 2]
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [0, -0.3u]
      asym: both
      size: 1u + 2
    - what: rectangle
      where:
        ref: matrix_middle_top
        shift: [1u, 0]
      asym: both
      size: [3u + 2, 1u + 2]
    - what: outline
      name: board_connector
  board:
    - what: outline
      name: board_raw
      fillet: BOARD_FILLET
  pcb_edge_support:
    - what: outline
      name: board_raw
      fillet: 0.5
      expand: -0.8  # must be less than 1mm
  case_outline:
    - what: outline
      name: board
      expand: WALL_THICKNESS
  plate_outline:
    - what: outline
      name: board
      expand: PLATE_EXTENSION
  wall: [
    +case_outline,
    -plate_outline,
  ]
  m2_holes:
    # Screw holes
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [matrix_inner_top, matrix_index_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [mirror_matrix_inner_top, mirror_matrix_index_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [matrix_outer_top, matrix_pinky_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [mirror_matrix_outer_top, mirror_matrix_pinky_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref: [matrix_ring_top]
        shift: [0.5u, -0.5u + 1]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref: [mirror_matrix_ring_top]
        shift: [0.5u, -0.5u + 1]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [matrix_inner_bottom, matrix_index_bottom]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [mirror_matrix_inner_bottom, mirror_matrix_index_bottom]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.4u, 0.5u + 0.3]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref: [mirror_matrix_pinky_bottom]
        shift: [0.4u, 0.5u + 0.3]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [thumbfan_inner_thumb, thumbfan_middle_thumb]
        shift: [0, 1.7]
    - what: circle
      radius: SCREW_SIZE/2
      where:
        ref.aggregate.parts: [mirror_thumbfan_inner_thumb, mirror_thumbfan_middle_thumb]
        shift: [0, 1.7]
  m2_spacers:
    # spacer holes
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [matrix_inner_top, matrix_index_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [mirror_matrix_inner_top, mirror_matrix_index_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [matrix_outer_top, matrix_pinky_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [mirror_matrix_outer_top, mirror_matrix_pinky_top]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref: [matrix_ring_top]
        shift: [0.5u, -0.5u + 1]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref: [mirror_matrix_ring_top]
        shift: [0.5u, -0.5u + 1]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [matrix_inner_bottom, matrix_index_bottom]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [mirror_matrix_inner_bottom, mirror_matrix_index_bottom]
        shift: [0, -0.5u]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref: [matrix_pinky_bottom]
        shift: [0.4u, 0.5u + 0.3]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref: [mirror_matrix_pinky_bottom]
        shift: [0.4u, 0.5u + 0.3]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [thumbfan_inner_thumb, thumbfan_middle_thumb]
        shift: [0, 1.7]
    - what: circle
      radius: SCREW_BORDER/2
      where:
        ref.aggregate.parts: [mirror_thumbfan_inner_thumb, mirror_thumbfan_middle_thumb]
        shift: [0, 1.7]
  # cutouts for the keys to be used in plate generation
  cutouts_mx:
    - what: rectangle
      where: true
      asym: source
      size: 14
  cutouts_choc:
    - what: rectangle
      where: true
      asym: source
      size: 13.8
  cutouts_extension:
    - what: rectangle
      where: true
      asym: source
      size: 18
  plate_mx: [
    +plate_outline,
    -cutouts_mx,
    -m2_holes,
  ]
  plate_choc: [
    +plate_outline,
    -cutouts_choc,
    -m2_holes,
  ]

#---------------------------------------------------------------------------------------------------
# Define the PCB, using a pro-micro layout
pcbs:
  fairyboard:
    outlines:
      fairyboard_pcb_outline:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap: true
      choc_hotswap:
        what: choc_compat
        where: true
        params:
          from: "{{colrow}}"
          to: "{{column_net}}"
          hotswap: true
        adjust:
          rotate: 180
      diodes_left:
        what: diode_smt_bottom
        where: -/mirror/
        adjust:
          shift: [7, -3.75]
          rotate: 90
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      diodes_right:
        what: diode_smt_bottom
        where: /mirror/
        adjust:
          shift: [-7, -3.75]
          rotate: -90
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      # Microcontroller
      mcu:
        what: nice_nano_elite_c
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, -0.615]
        params:
          flipped: true
          label: false
          P006: D0
          P008: D1
          P017: D2
          P020: D3
          P022: D4
          P024: ROW1
          P100: ROW3
          P011: ROW6
          P104: ROW4
          P106: ROW7

          P031: COL1
          P029: COL2
          P002: COL3
          P115: COL4
          P113: COL5
          P111: COL6
          P010: ROW2
          P009: ROW5

          # nice!nano specific pins
          P101: D5
          P102: D6
          P107: D7

          # elite c specific pins
          B7: D5
          D5: D6
          C7: D7
          F1: D8
          F0: D9
      # nice!view screen
      display:
        what: nice_view
        params:
          MOSI: D2
          SCK: D3
          CS: D0
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, -3.394]
      # Four Pin Reset Button
      reset:
        what: reset_switch_tht_side
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [-18, 4.5]
      # Battery switch
      battery_switch:
        what: slider
        params:
          from: RAW
          to: B+
        where:
          ref.aggregate.parts: [matrix_index_top, mirror_matrix_index_top]
          shift: [18, 6]
      # Battery connector
      battery_connector:
        what: jstph
        params:
          pos: B+
          neg: GND
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [15, -0.476]
      # Terminal block for Trackball/point breakout
      terminal_block_8:
        what: terminal_block_8
        params:
          label_side: top
          RAW: RAW
          VCC: VCC
          GND: GND
          D0: D0
          D1: D1
          D2: D2
          D3: D3
          D4: D4
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [-21, -3.394]
      # Terminal block for extra pins breakout
      terminal_block_5:
        what: terminal_block_5
        params:
          label_side: top
          D5: D5
          D6: D6
          D7: D7
          D8: D8
          D9: D9
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [19.79, -3.394]
      # Screw holes
      hole_top_inner_left:
        what: spacerhole
        where:
          ref.aggregate.parts: [matrix_inner_top, matrix_index_top]
          shift: [0, -0.5u]
      hole_top_inner_right:
        what: spacerhole
        where:
          ref.aggregate.parts: [mirror_matrix_inner_top, mirror_matrix_index_top]
          shift: [0, -0.5u]
      hole_top_outer_left:
        what: spacerhole
        where:
          ref.aggregate.parts: [matrix_outer_top, matrix_pinky_top]
          shift: [0, -0.5u]
      hole_top_outer_right:
        what: spacerhole
        where:
          ref.aggregate.parts: [mirror_matrix_outer_top, mirror_matrix_pinky_top]
          shift: [0, -0.5u]
      hole_top_middle_left:
        what: spacerhole
        where:
          ref: [matrix_ring_top]
          shift: [0.5u, -0.5u + 1]
      hole_top_middle_right:
        what: spacerhole
        where:
          ref: [mirror_matrix_ring_top]
          shift: [0.5u, -0.5u + 1]
      hole_bot_inner_left:
        what: spacerhole
        where:
          ref.aggregate.parts: [matrix_inner_bottom, matrix_index_bottom]
          shift: [0, -0.5u]
      hole_bot_inner_right:
        what: spacerhole
        where:
          ref.aggregate.parts: [mirror_matrix_inner_bottom, mirror_matrix_index_bottom]
          shift: [0, -0.5u]
      hole_bot_outer_left:
        what: spacerhole
        where:
          ref: [matrix_pinky_bottom]
          shift: [0.4u, 0.5u + 0.3]
      hole_bot_outer_right:
        what: spacerhole
        where:
          ref: [mirror_matrix_pinky_bottom]
          shift: [0.4u, 0.5u + 0.3]
      hole_thumb_left:
        what: spacerhole
        where:
          ref.aggregate.parts: [thumbfan_inner_thumb, thumbfan_middle_thumb]
          shift: [0, 1.7]
      hole_thumb_right:
        what: spacerhole
        where:
          ref.aggregate.parts: [mirror_thumbfan_inner_thumb, mirror_thumbfan_middle_thumb]
          shift: [0, 1.7]
      window_hole_bot_left:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [0.5u + 7.5, -0.3u]
      window_hole_bot_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_top]
          shift: [0.5u + 7.5, -0.3u]
      window_hole_top_left:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [0.5u + 7.5, 0.5u]
      window_hole_top_right:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_top]
          shift: [0.5u + 7.5, 0.5u]

#---------------------------------------------------------------------------------------------------
# Simple case parts
cases:

  # common bottom for all cases
  _bottom:
    - name: case_outline
      extrude: BOTTOM_THICKNESS
    - name: m2_holes
      extrude: BOTTOM_THICKNESS
      operation: subtract

  # wall construction
  _wall_low:
    - name: wall
      extrude: BOTTOM_THICKNESS + 4.6
  _wall_mid_mx:
    - name: wall
      extrude: BOTTOM_THICKNESS + 9.6
    - name: board_connector_cutout
      extrude: BOTTOM_THICKNESS + 9.6
      operation: subtract
    - what: case
      name: _wall_low
      operation: add
  _wall_high_mx:
    - name: wall
      extrude: BOTTOM_THICKNESS + 15.8
    - name: board_connector_cutout
      extrude: BOTTOM_THICKNESS + 15.8
      operation: subtract
    - what: case
      name: _wall_low
      operation: add

  # plate
  plate_mx:
    - name: plate_mx
      extrude: PLATE_THICKNESS
    - name: board_connector_extended
      extrude: PLATE_THICKNESS
      operation: subtract

  # final cases
  case_lowpro:
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall_low
      operation: add
  case_midpro_mx:
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall_mid_mx
      operation: add
  case_hipro_mx:
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall_high_mx
      operation: add

  # testing plate for shape and sizing
  testing_plate_mx:
    - name: plate_mx
      extrude: BOTTOM_THICKNESS + 9.6
    - name: board_connector_extended
      extrude: BOTTOM_THICKNESS + 9.6
      operation: subtract
    - what: case
      name: case_midpro_mx
